### ISSUE TITLE
Sedimentation tank channel design code

### ISSUE THREAD

**Issue by fletchapin** [AguaClara/aguaclara#39]
Take the CEE 4540 final project done by H2Flows to calculate the dimensions of the inlet and exit channels and convert it to a python script which could be used to calculate channel dimensions.

Because the channels will be constant width we will not have to use most of this code, just the portion that calculates the length of the channel. However, it will be good to have the code there in case we want to change the width of the channels in the future and to document how the constant width was originally calculated.

**Comment by fletchapin** [comment]
@monroews is the nominal diameter of the launder constant? In the design challenge it wasn't given, and we can't find a record of it in Mathcad.

In the final project from 4540 the value used was 1 inch, but we're not sure where that came from.

**Comment by monroews** [comment]
I checked the Sedimentation Tank.xmcd.
NS.SedLaunder is calculated using NS.Manifold that is in the fluids functions.

These functions should be used because if someone ever makes a wider sed tank it will be critical that the launder pipes scale correctly.

The launder pipes are about 6 inches in diameter for our full length sed tanks.

**Comment by zoemaisel** [comment]
@CynthiaTChan We will define a constant value for the channel widths so that we can have an overall constant sedimentation length. However, we will want to create the functions that give the ability for the channel width to vary. We will ask you to use Mathcad and the H2Flows 4540 project to create those functions.

**Comment by eak24** [comment]
Is this still relevant?

**Comment by oliver-leung** [comment]
Closing as this issue hasn't been responded to in a while.

**Comment by fletchapin** [comment]
Sorry didn't see @ethan92429 comment a month ago. This is still relevant in that it never got done last semester, but it's not pressing so I'd put it on the back burner but leave the issue open. Maybe we could create a `backlog` tag to sort issues like this by but keep them open?

**Comment by oliver-leung** [comment]
This has been done in #175 , including the above mentioned calculations of launder (now called outlet manifold) ND and channel width.
