### ISSUE TITLE
Filter design code

### ISSUE THREAD

**Issue by fletchapin** [AguaClara/aguaclara#48]
We need to create all functions necessary to design the filter and make the accompanying template

**Comment by oliver-leung** [comment]
We have begun implementing this according to the details in [this document](https://docs.google.com/document/d/1h2indq8umJFX3futgzzfoL5UQIKdB7qtXdhg_pGej2Q/edit).

On Thursday (4/18), I met with Monroe to plan out the specifications of the filter, which I've detailed above.

**Comment by oliver-leung** [comment]
Reviewed and made small edits to current code

**Comment by oliver-leung** [comment]
Didn't work on this due to focusing on final presentations.

**Comment by oliver-leung** [comment]
We will be picking back up on this task as we move into the next semester! @monroews has created a [Google Colab notebook](https://drive.google.com/open?id=1EmkMPzNQDPrhXUpfW82TXKl5p8NnfeB7) that details the design logic that we will be using to design the filter.

We are currently planning on structuring our classes as follows:
- Filter
  - Inlet
    - Channel
    - Tank
    - Pipelines
  - Tank (formerly "filter box")
  - Outlet
    - Pipelines
    - Channel
  - Backwash Assembly

The reason for this is so that we can centralize the calculations around the filter tank. Once we make calculations for the inlet flow (from channel to each inlet branch) and outlet flow (from each outlet branch to channel), we believe that we can make simpler calculations with regards to the filter tank's sand layers.

Let us know if there are any suggestions on this process!

**Comment by Henry262799** [comment]
The design functions are deprecated
