### ISSUE TITLE
Make cdc_functions more readable and add unittests

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/aguaclara#5]
I made a PR review that details some issues with the cdc_functions: https://github.com/AguaClara/aide_design/pull/4#pullrequestreview-61515198  I unfortunately had to merge before we could fix these problems, but they still should be fixed. I added a couple small tests to a test_cdc_functions unittest to get you started on a comprehensive test suite for the cdc_functions module.

**Comment by ethan92429** [comment]
I'm writing some unittests to start this process. I'll just add them as another commit in the monroe's aide branch.

**Comment by ethan92429** [comment]
@monroews: One quick comment while I remember. It's more philosophical than anything: The branch: "Monroe's-aide" has two problems. First, and most importantly, it doesn't describe what feature you are adding on this branch. Next time you name a branch, ask what feature the branch will integrate, or what it will do in general. Next issue, avoid apostrophes for the command line lovers and try to make the name python_like!

**Comment by ethan92429** [comment]
@monroews can I delete the research file, the process_draw folder and the Tutorial of Coagulant and Clay System Design python notebook? Of course, nothing is actually deleted - just won't be submitted in the next commits - but you could always checkout the last commit with those files. Also, the latest flow control notebook as you committed it had an error with the code after Q #15, where it references Ratio_Linear_CDC_Error variable, yet that is never locally defined. I assume you meant: exp.RATIO_LINEAR_CDC_ERROR, (as defined in expert inputs) but I'm unclear how you could run the notebook all the way through without that change? Is it possible I still have the wrong commit, or does your local copy also have that issue when you try to run it?

**Comment by monroews** [comment]
Ethan,
I'm copying Cynthia on this too because we might use Tutorial of Coagulant
and Clay System Design tutorial for the project teams.

My copy of the flow control and measurement notebook works. And i haven't
done anything to it since pushing it github.

That is an example of a variable that should probably be in the function
calls, but have a default value that refers to exp.



Monroe Weber-Shirk

AguaClara <http://aguaclara.cornell.edu/> at Cornell
Civil and Environmental Engineering <http://www.cee.cornell.edu/>
Cornell University <http://www.cornell.edu/>
Hollister Hall 265
(607) 216-8445
<http://aguaclara.cornell.edu/>

**Comment by ethan92429** [comment]
@juanchon998 please see the comment about branching above! Branch's shouldn't be named "juan's branch"

**Comment by eak24** [comment]
This isn't relevant
