### ISSUE TITLE
Variable naming guide needs to provide guidance for naming complex variables

### ISSUE THREAD

**Issue by monroews** [AguaClara/aguaclara#87]
The current naming guide provides excellent capitalization and name guidance, but it doesn't explain how to assemble a full variable name that combines multiple words. For example
B_sed_plate.

**Comment by oliver-leung** [comment]
Not sure if this has been resolved, but we proposed a method within [AIDE's first Summer Report](https://github.com/AguaClara/aide/blob/master/reports/AIDE_Summer2018report.md). In general, every word within a variable name should be ordered from the highest to the lowest hierarchical level, from left to right.

For a more intuitive approach, each variable name should be ordered such that words can be removed from the _right_ and the name would still "make sense". Suppose that a variable name is `n_lfom_rows`. This is incorrectly named because `n_lfom` doesn't make sense in the context of how the design is organized. Now, suppose that the variable name is `lfom_rows_n`. This is correctly named because `lfom_rows` and `lfom` still make sense in the context of the design hierarchy.

**Comment by ethan92429** [comment]
I think I may be misunderstanding what this issue refers to... within aide_render, the template naming convention is to define certain named objects that have properties. For instance, instead of having some long name to get to b_sed_plate, there is an object within sed that is plate, and a variable within sed that is b_plate. So for instance, to get at b_plate given a plant, one would use plant.sed.b_plate . That would "tunnel in" to b_plate. This should be reflected within the naming guide. 

However, there is confusion within aide_design because aide_design doesn't know about those relationships (aide_design just being a simple collection of functions). So how do we name things within aide_design?

**Comment by oliver-leung** [comment]
I think a good start is to remove any redundant function names within the classes. For example, in `functions/lfom.py` in the `filter_design` branch, there's a function `n_lfom_rows`. A call to this function would look like `lfom.n_lfom_rows`, but it would make a lot more sense to make it `lfom.rows_n`. That way, it follows the hierarchical naming method in that you can remove words from the right and the name would still make sense.

**Comment by ethan92429** [comment]
I like that this removes some of the redundancy. I think we could simplify things by incorporating aide_design with aide_render. Then, we can "mask" the class behavior of LFOM by importing LFOM directly within aide_design.play. It would look like: 
` import lfom.LFOM as LFOM`
That would import all the functions within the LFOM class. a call to LFOM.n_rows would return the number of rows. Then, to create an LFOM, one would run:
`my_lfom = LFOM(q=20*u.L/s). `
And then, to determine the number of rows:
`my_lfom.n_rows()
`The behavior of the LFOM class would be such that you could still create it without any variables...
like: `my_lfom = LFOM()` but then if you try to query `LFOM.n_rows()`, you'll get a `self.q is not defined` error. This is the approach we use within aide_render, and I don't see any reason we shouldn't organize the unit-process specific functions into these classes.

**Comment by eak24** [comment]
Irrelevant to new system. The new system is rather modularized such that having one global system would be inflexible and time consuming. Rather, the key here is to create documentation that outlines attributes of all the various design classes.
